# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-uat
  namespace: default
  labels:
    app: go-web-app-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app-uat
  template:
    metadata:
      labels:
        app: go-web-app-uat
    spec:
      containers:
      - name: go-web-app-uat
        image: pranav1562/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080